### ISSUE TITLE
生成offline文件会报错

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/tw-mobile-sync#22]
本地上使用是不会报错的。但我推上去，生成的网站会报错。

![3~S(%4NFH 4BR}467OM1 R](https://github.com/tiddly-gittly/tw-mobile-sync/assets/109711900/360bebae-ad54-4762-b7ae-f70563251c63)

![image](https://github.com/tiddly-gittly/tw-mobile-sync/assets/109711900/0b35e45b-eb60-457c-99b2-819526476ef4)

后面我删除了这个插件也同样会报错。

因为我想生成offline文件，然后用[https://github.com/tiddly-gittly/TW5-T-ONLINE](url)的一些配置文件。就出现上面的问题了。正常直接使用太记默认模板不会出现上面的问题。（应该吧，因为我不怎么用这个插件。唯一一个用的是私人wiki。）更新的时候或许可以排查一下这个问题。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/tw-mobile-sync/assets/109711900/5a0a261b-6336-4ccc-8301-c411b3966371)

她的示例中，只有一个核心插件和图片引用插件，可能没遇到这样的问题。

**Comment by linonetwo** [comment]
就是这个问题 https://github.com/twcloud/tiddlyweb-sse/issues/4

可以去催一下那个作者

**Comment by dongrentianyu** [comment]
删除这个插件就没事了。我关了这个issue了。
