### ISSUE TITLE
在手机端tiddloid中更改某一个条目的title字段，点击同步后，未同步原条目，而是新建了新的条目。

### ISSUE THREAD

**Issue by wwhiffle** [tiddly-gittly/tw-mobile-sync#28]
1. 描述：
    - 在手机端更改条目名称，比如把一个条目的名称 “111” 改为 “222” ，然后点击同步，电脑上的条目 “111” 未改变，但直接增加了一个新的条目 “222” 。此时手机端只有一个修改过的条目 “222” ，电脑端有两个条目——条目 “111” 和条目 “222” 。这可能是因为`tw-mobile-sync`插件把 “修改过名称的条目” 当作 “刚创建的新条目” 同步了。

2. 问题：
    1. 插件是根据title字段的值来对应“原条目”和“修改后的条目”吗？
    2. 为什么不根据对于每一个条目而言都独一无二的created字段的值来对应“原条目”和“修改后的条目”呢？

3. 请求
    - 能否同步“修改过名称的条目”呢

**Comment by linonetwo** [comment]
duplicate https://github.com/tiddly-gittly/tw-mobile-sync/issues/7
